apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotelbookingclient-deployment
spec:
  selector:
    matchLabels:
      app: hotelbookingclient
  replicas: 1
  template:
    metadata:
      labels:
        app: hotelbookingclient
    spec:
      containers:
        - name: hotelbookingclient
          image: abdiaoo/hotelbooking-webapp:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: hotelbookingclient-service
spec:
  type: ClusterIP
  selector:
    app: hotelbookingclient
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
