apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotelbookingapi-deployment
spec:
  selector:
    matchLabels:
      app: hotelbookingapi
  replicas: 1
  template:
    metadata:
      labels:
        app: hotelbookingapi
    spec:
      containers:
        - name: hotelbookingapi
          image: abdiaoo/hotelbooking-backendapp:latest
          ports:
            - containerPort: 8070
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: host
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
---
apiVersion: v1
kind: Service
metadata:
  name: hotelbookingapi-service
spec:
  selector:
    app: hotelbookingapi
  ports:
    - port: 8070
      targetPort: 8070
      protocol: TCP
  type: ClusterIP
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: hotelbooking-ingress
# spec:
#   rules:
#   - http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: hotelbookingbackendapp-service
#             port:
#               number: 8070