apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hotelbooking-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: hotelbooking
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hotelbookingwebapp
                port:
                  number: 81
