name: Github Action Build Hotel Booking App Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up && Build with Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.6.3

      - name: Build backend spring app with Maven
        run: mvn -f ./bookinghotelbackend/pom.xml --batch-mode --update-snapshots clean install -DskipTests

      - name: Build Docker images
        run: docker compose build

      - name: List Docker images
        run: docker images

      - name: Stop Containers
        if: always()
        continue-on-error: true
        run: docker compose down -v
