name: Github Action Build Hotel Booking App Workflow
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      -
      - name: Set up && Build with Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.6.3
      - name: Build backend spring app with Maven
        run: mvn -f ./bookinghotelbackend/pom.xml --batch-mode --update-snapshots clean install -DskipTests
